### ISSUE TITLE
ValueError: Problem accessing HEAD branch: https://github.com/Intercoonecta/OHW2024

### ISSUE THREAD

**Issue by ctroupin** [Intercoonecta/Intercoonecta.github.io#18]
Buenos días,

no sé si me equivoco en una parte del proceso, pero en la web https://intercoonecta.github.io/primeros-pasos.html, se indica
> Para actualizar los tutoriales en la plataforma, [sigan estas instrucciones](https://intercoonecta.github.io/primeros-pasos.html#como-consigo-el-repositorio-de-los-tutoriales-en-el-hub)

donde encontramos en enlace: [Haga pull del repositorio de los para el perfil de Python](https://oceanhackweek.2i2c.cloud/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2FIntercoonecta%2FOHW2024&urlpath=lab%2Ftree%2FOHW2024)

Sin embargo este enlace da un error, me imagino porque https://github.com/Intercoonecta/OHW2024 no existe, tendría que ser https://github.com/Intercoonecta/tutorialesOHW2024

```python
Traceback (most recent call last):
File "/home/.pixi/envs/default/lib/python3.12/site-packages/nbgitpuller/pull.py", line 118, in resolve_default_branch
    head_branch = subprocess.run(
                  ^^^^^^^^^^^^^^^
File "/home/.pixi/envs/default/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'ls-remote', '--symref', '--', 'https://github.com/Intercoonecta/OHW2024', 'HEAD']' returned non-zero exit status 128.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/home/.pixi/envs/default/lib/python3.12/site-packages/nbgitpuller/handlers.py", line 87, in get
    gp = GitPuller(repo, repo_dir, branch=branch, depth=depth, parent=self.settings['nbapp'])
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/.pixi/envs/default/lib/python3.12/site-packages/nbgitpuller/pull.py", line 79, in __init__
    self.branch_name = self.resolve_default_branch()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/.pixi/envs/default/lib/python3.12/site-packages/nbgitpuller/pull.py", line 134, in resolve_default_branch
    raise ValueError(m)
ValueError: Problem accessing HEAD branch: https://github.com/Intercoonecta/OHW2024
``

**Comment by emiliom** [comment]
Qué extraño! Yo actualizé eso ayer y estoy seguro que estaba bien. Efectivamente, tiene que ser `tutorialesOHW2024` donde actualmente ocurre `OHW2024`. Acabo de corregirlo. Gracias por hacer esta observacion.

**Comment by ctroupin** [comment]
Thanks,
ahora todo correcto!
