### ISSUE TITLE
traducción página project overview

### ISSUE THREAD

**Issue by LauraGomezNavarro** [Intercoonecta/Intercoonecta.github.io#6]
@emiliom aquí está la traducción de la página : https://oceanhackweek.org/resources/projects/index.html

# Project Overview
Los proyectos colaborativos son un componente clave del hackatón, en los que puedes interactuar con otras personas de cerca y aplicar nuevas habilidades para hacer que algo emocionante suceda: puede ser la creación de herramientas para optimizar el acceso a una fuente de datos en particular, visualizar algunos datos de alta densidad de forma interactiva, probar modelos existentes con nuevas fuentes de datos, o cualquier otra cosa que desee hacer en la intersección de la oceanografía y la ciencia de datos.

## ¿Qué es un Hack?
Un "hack" es un pequeño proyecto que tiene como objetivo resolver un problema específico utilizando herramientas computacionales.

Algunos ejemplos de "hacks":
* Construir una demostración de trabajo de un algoritmo nuevo o modificado
* Esquema de un proyecto más grande, con algunas características clave exploradas
* Visualización de un conjunto de datos antiguo de una manera nueva
* Modificar un algoritmo y aplicarlo a un nuevo conjunto de datos
* Combinar dos piezas de código preexistentes para realizar alguna nueva función
* Crear una herramienta para aplicar al trabajo con código existente, conjuntos de datos
* Transformar código de un idioma a otro para usarlo con otras herramientas
* Actualizar código antiguo para que funcione más rápido, en máquinas nuevas y/o más eficientemente
* Ampliar un proyecto existente con una función adicional
* Simplificar código para que sea más sostenible, también conocido como "pagar la deuda técnica"

## ¿Por qué hackear en este hackatón?
Cada vez más, la investigación y el desarrollo de software son realizados por grupos de personas con diversas habilidades y experiencias.  Creemos que este trabajo colaborativo conduce a soluciones más innovadoras a problemas complejos. ~~En el hackatón, Creemos que este trabajo colaborativo conduce a soluciones más innovadoras a problemas complejos.~~ En OceanHackWeek, nuestro objetivo es explorar con usted algunas de las habilidades necesarias para navegar por los desafíos técnicos y sociales de trabajar en este tipo de entornos colaborativos.  Creemos que la mejor manera de hacerlo es proporcionarle oportunidades de adquirir experiencia práctica en el trabajo conjunto con otras personas sobre un problema bien definido relacionado con las ciencias marinas.

**Comment by emiliom** [comment]
Muchas gracias @LauraGomezNavarro !  Está perfecto. Sólo le hice una corrección, al eliminar una oración repetida.

**Comment by emiliom** [comment]
Incorporado en el PR #8
