### ISSUE TITLE
traducción página getting started

### ISSUE THREAD

**Issue by LauraGomezNavarro** [Intercoonecta/Intercoonecta.github.io#9]
@emiliom aquí está la traducción de la página : https://oceanhackweek.org/resources/tutorials/getting_started.html 

Solo queda actualizar los enlaces de Python (https://oceanhackweek.2i2c.cloud/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Foceanhackweek%2Fohw-tutorials&urlpath=lab%2Ftree%2Fohw-tutorials%2F&branch=OHW22) y R (https://oceanhackweek.2i2c.cloud/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Foceanhackweek%2Fohw-tutorials&urlpath=rstudio%2F&branch=OHW22)

# Primeros pasos para los tutoriales

## Introducción

Los tutoriales se ejecutarán en vivo en el [JupyterHub  del hackatón ("El Hub"), https://oceanhackweek.2i2c.cloud](https://oceanhackweek.2i2c.cloud) en su navegador, ya sea como _Jupyter notebooks_ o como _scripts_ y _notebooks_ en RStudio. El/la instructor/a y todas las personas que participen pueden estar ejecutando sus propias copias del tutorial en su cuenta del Hub, con archivos clonados desde la fuente en GitHub.

A continuación hay instrucciones para iniciar los tutoriales en el Hub en su navegador y actualizar los archivos de los tutoriales con la última versión del repositorio de tutoriales GitHub, [https://github.com/Intercoonecta/tutoriales](https://github.com/Intercoonecta/tutoriales).

El calendario de tutoriales está disponible [aquí](https://github.com/Intercoonecta/tutoriales/blob/main/README.md), y los enlaces a los materiales de los tutoriales y algunos otros recursos estarán disponibles allí también.

## ¿Cómo consigo el repositorio de los tutoriales en el Hub?

Para los tutoriales, recomendamos el uso de [nbgitpuller](https://jupyterhub.github.io/nbgitpuller/) para clonar y extraer el repositorio de los tutoriales, o actualizar la copia que ya tiene. Utilice el enlace mágico nbgitpuller a continuación para lograr este clon o actualización.

```{admonition} Haga _pull_ del repositorio de los tutoriales usando la magía de nbgitpuller

El enlace nbgitpuller es mágico, pero no puede detectar qué perfil está ejecutando actualmente.  El enlace nbgitpuller es mágico, pero no puede detectar qué perfil está ejecutando actualmente. Debería o actualizar el (mismo) repositorio de los tutoriales, pero podría dar un error si utiliza el enlace de Python si está utilizando activamente el perfil R, o al revés.

::::{tab-set}

:::{tab-item} Python

[Haga pull del repositorio de los tutoriales para el perfil de Python](https://oceanhackweek.2i2c.cloud/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Foceanhackweek%2Fohw-tutorials&urlpath=lab%2Ftree%2Fohw-tutorials%2F&branch=OHW22)

:::

:::{tab-item} R

[Haga pull del repositorio de los tutoriales para el perfil de R](https://oceanhackweek.2i2c.cloud/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Foceanhackweek%2Fohw-tutorials&urlpath=rstudio%2F&branch=OHW22)

:::

::::

```

Vea esta [discusión extendida] (../prep/jupyterhub.md#how-do-i-get-the-tutorial-repository) para más detalles sobre `nbgitpuller` y el enfoque alternativo basado en comandos `git` y los flujos de trabajo `GitHub`.

**Comment by emiliom** [comment]
Ya incorporé tu traducción al sitio (https://intercoonecta.github.io/primeros-pasos.html), después de actualizar los enlaces y otros detallitos. ¡Muchas gracias!
